name: Test

on:
  push:
    branches:
      - main
      - updated
      - dev
      
  pull_request:
    branches:
      - main
      - updated
      - dev

jobs:
  unit:
    name: Unit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Test
        shell: bash
        run: |
          make test_cover

      - name: Store coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: unit.coverprofile

  integration:
    name: Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Services
        shell: bash
        run: |
          make run && sleep 15

      - name: Test
        shell: bash
        run: |
          make test_integration_cover

      - name: Store coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: integration.coverprofile

  finish:
    name: Finish
    runs-on: ubuntu-latest
    needs: [unit, integration]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Load coverage
        uses: actions/download-artifact@v4
        with:
          name: coverage

      - name: Merge coverage
        shell: bash
        run: |
          make merge_coverage

      - name: Convert coverage
        uses: jandelgado/gcov2lcov-action@v1.0.9
        with:
          infile: coverage.out
          outfile: coverage.lcov

      - name: Upload coverage
        uses: coverallsapp/github-action@v2.2.3
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: coverage.lcov
